bitmaps["loading"] := Gdip_BitmapFromBase64("iVBORw0KGgoAAAANSUhEUgAAAGQAAABkAQMAAABKLAcXAAAAA1BMVEUiV6ixRE8dAAAAE0lEQVR42mMYBaNgFIyCUUBXAAAFeAABSanTpAAAAABJRU5ErkJggg==")
bitmaps["science"] := Gdip_BitmapFromBase64("iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKAQMAAAC3/F3+AAAAA1BMVEX0qQ0Uw53LAAAACklEQVR42mPACwAAHgAB3XenRQAAAABJRU5ErkJggg==")
bitmaps["FriendJoin"] := Map()
bitmaps["FriendJoin"][1] := Gdip_CreateBitmap(100,4), pGraphics := Gdip_GraphicsFromImage(bitmaps["FriendJoin"][1]), Gdip_GraphicsClear(pGraphics, 0xff393B3D), Gdip_DeleteGraphics(pGraphics)
bitmaps["FriendJoin"][2] := Gdip_CreateBitmap(100,4), pGraphics := Gdip_GraphicsFromImage(bitmaps["FriendJoin"][2]), Gdip_GraphicsClear(pGraphics, 0xff272930), Gdip_DeleteGraphics(pGraphics)
