#Requires AutoHotkey v2.0

SetWorkingDir A_ScriptDir "\.."

#include "%A_ScriptDir%\..\lib\"
#include "HashFile.ahk"
#include "JSON.ahk"

patterns := []

Msgbox "Make sure there are no custom patterns installed."

outputPath := "lib\data\patternHashes.ahk"
hashes := ""

output := FileOpen(outputPath, "w")

loop files "patterns/*.ahk" {
    fileHash := HashFile(A_LoopFileFullPath, 6)
    hashes .= "`t`"" fileHash "`",`s; " StrReplace(A_LoopFileName, ".ahk") "`r`n"
}

output.Write("defaultPatternHashes := [`s; Generated by tools/hashDefaultPatterns.ahk`r`n" hashes "]`r`n")
output.Close()
